### ISSUE TITLE
Feature: IPv6

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/calico#595]
Calico supports IPv6, but there are a number of missing areas at the moment.  This issue tracks the outstanding work left for this feature.

- [x] Documentation (#N/A)
- [x] Support for IPv6 in individual components
  - [x] CNI Plugin Support (#N/A)
  - [x] Libnetwork plugin support (https://github.com/projectcalico/calico/issues/227)
  - [X] Handle IPv6 when using KDD (issue #1703)
  - [x] Calico Node requires IPv4 (issue #1204)

Please keep this issue up to date with the latest status.

[List of GitHub issues which mention IPv6](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+user%3Aprojectcalico+ipv6)

**Comment by caseydavenport** [comment]
Closing since I don't think there's much value left in this one.
