### ISSUE TITLE
Improve/Add Usage docs for some common Calico tasks

### ISSUE THREAD

**Issue by tmjd** [projectcalico/calico#778]
This is a summary issue around improving the docs in our Usage section.

- [x] Installing & Configuring calicoctl (#632)
  - Link to orchestrator specific directions too
    - Link to k8s specific docs from #762
- [x] Manipulating IP Pools
  - Adding, Modifying, Deleting
- [x] Configuring MTU (#659)
- [ ] Improve BGP (& RR) Documentation (#584)
- [x] Delete unused node / remove one that IP Address changed (#312)
- [x] Using a host endpoint for an external host to allow labels to be used in policy for the host IPs (#818)

**Comment by ozdanborne** [comment]
for 1a - my PR on using calicoctl in k8s is merged: #762

**Comment by tmjd** [comment]
This issue is around fleshing out the "Usage" section docs but the installing & configuring calicoctl should certainly link to the k8s specific info too.

**Comment by caseydavenport** [comment]
Since the last thing here is tracked in #584, I'm going to close this since I don't think it's valuable any more.
